### ISSUE TITLE
Hi friends, have you resolved this issue,memoryerror ?  

### ISSUE THREAD

**Issue by zhangpengk** [guchengxi1994/RTV-in-Python#1]

**Comment by guchengxi1994** [comment]
if you are a student in college, i think matlab is more suitable for this algorithm.
otherwise, convert matrix type to np.float32 maybe work. 
if you use a linux system, try to set a really large virtual memory.
if you do have a matlab on your computer but you still want to try this algorithm in python ,[this may help](https://blog.csdn.net/weixin_41521681/article/details/96499305).

**Comment by zhangpengk** [comment]
@guchengxi1994  thanks for  your guidance !  i will try it again 。
